// AUTO-GENERATED by wrappergen's `emit_typescript_facade` -- do not edit by hand.
import * as native from "./ifcopenshell_napi_spike.node";

export type IfcopenshellAttributeValueVariantT = {
    kind: number;
    integer_value?: unknown;
    integer_value?: unknown;
    logical_value?: unknown;
    integer_value?: unknown;
    double_value?: unknown;
    string_value?: unknown;
    string_value?: unknown;
    entity_value?: unknown;
};

export class exception {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    static with_message(message: string): exception {
        return new exception(native.exception_new_with_message(message));
    }

}

export class attribute_out_of_range_exception {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    static with_message(message: string): attribute_out_of_range_exception {
        return new attribute_out_of_range_exception(native.attribute_out_of_range_exception_new_with_message(message));
    }

}

export class invalid_token_exception {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    static with_token_start_token_string_expected_type(token_start: number, token_string: string, expected_type: string): invalid_token_exception {
        return new invalid_token_exception(native.invalid_token_exception_new_with_token_start_token_string_expected_type(token_start, token_string, expected_type));
    }

}

export class parameter_type {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    as_named_type(): named_type {
        const result = native.parameter_type_as_named_type(this._handle);
        return result === null ? null as unknown as named_type : new named_type(result);
    }

    as_simple_type(): simple_type {
        const result = native.parameter_type_as_simple_type(this._handle);
        return result === null ? null as unknown as simple_type : new simple_type(result);
    }

    as_aggregation_type(): aggregation_type {
        const result = native.parameter_type_as_aggregation_type(this._handle);
        return result === null ? null as unknown as aggregation_type : new aggregation_type(result);
    }

    is__with_arg0_overload_1(arg0: string): boolean {
        return native.parameter_type_is_with_arg0_overload_1(this._handle, arg0);
    }

    is__with_arg0_overload_2(arg0: declaration): boolean {
        return native.parameter_type_is_with_arg0_overload_2(this._handle, arg0);
    }

}

export class named_type {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    static with_declared_type(declared_type: declaration): named_type {
        return new named_type(native.named_type_new_with_declared_type(declared_type));
    }

    declared_type(): declaration {
        const result = native.named_type_declared_type(this._handle);
        return result === null ? null as unknown as declaration : new declaration(result);
    }

    as_named_type(): named_type {
        const result = native.named_type_as_named_type(this._handle);
        return result === null ? null as unknown as named_type : new named_type(result);
    }

    is__with_name(name: string): boolean {
        return native.named_type_is_with_name(this._handle, name);
    }

    is__with_decl(decl: declaration): boolean {
        return native.named_type_is_with_decl(this._handle, decl);
    }

}

export class simple_type {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    as_simple_type(): simple_type {
        const result = native.simple_type_as_simple_type(this._handle);
        return result === null ? null as unknown as simple_type : new simple_type(result);
    }

}

export class aggregation_type {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    bound1(): number {
        return native.aggregation_type_bound1(this._handle);
    }

    bound2(): number {
        return native.aggregation_type_bound2(this._handle);
    }

    type_of_element(): parameter_type {
        const result = native.aggregation_type_type_of_element(this._handle);
        return result === null ? null as unknown as parameter_type : new parameter_type(result);
    }

    as_aggregation_type(): aggregation_type {
        const result = native.aggregation_type_as_aggregation_type(this._handle);
        return result === null ? null as unknown as aggregation_type : new aggregation_type(result);
    }

}

export class declaration {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    static with_name_index_in_schema(name: string, index_in_schema: number): declaration {
        return new declaration(native.declaration_new_with_name_index_in_schema(name, index_in_schema));
    }

    name(): string {
        return native.declaration_name(this._handle);
    }

    name_uc(): string {
        return native.declaration_name_uc(this._handle);
    }

    as_type_declaration(): type_declaration {
        const result = native.declaration_as_type_declaration(this._handle);
        return result === null ? null as unknown as type_declaration : new type_declaration(result);
    }

    as_select_type(): select_type {
        const result = native.declaration_as_select_type(this._handle);
        return result === null ? null as unknown as select_type : new select_type(result);
    }

    as_enumeration_type(): enumeration_type {
        const result = native.declaration_as_enumeration_type(this._handle);
        return result === null ? null as unknown as enumeration_type : new enumeration_type(result);
    }

    is__with_name(name: string): boolean {
        return native.declaration_is_with_name(this._handle, name);
    }

    is__with_decl(decl: declaration): boolean {
        return native.declaration_is_with_decl(this._handle, decl);
    }

    index_in_schema(): number {
        return native.declaration_index_in_schema(this._handle);
    }

    type(): number {
        return native.declaration_type(this._handle);
    }

    schema(): schema_definition {
        const result = native.declaration_schema(this._handle);
        return result === null ? null as unknown as schema_definition : new schema_definition(result);
    }

}

export class type_declaration {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    static with_name_index_in_schema_declared_type(name: string, index_in_schema: number, declared_type: parameter_type): type_declaration {
        return new type_declaration(native.type_declaration_new_with_name_index_in_schema_declared_type(name, index_in_schema, declared_type));
    }

    declared_type(): parameter_type {
        const result = native.type_declaration_declared_type(this._handle);
        return result === null ? null as unknown as parameter_type : new parameter_type(result);
    }

    as_type_declaration(): type_declaration {
        const result = native.type_declaration_as_type_declaration(this._handle);
        return result === null ? null as unknown as type_declaration : new type_declaration(result);
    }

}

export class select_type {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    select_list(): declaration[] {
        const result = native.select_type_select_list(this._handle) as unknown[];
        return result.map((item) => new declaration(item));
    }

    as_select_type(): select_type {
        const result = native.select_type_as_select_type(this._handle);
        return result === null ? null as unknown as select_type : new select_type(result);
    }

}

export class enumeration_type {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    lookup_enum_offset(value_name: string): number {
        return native.enumeration_type_lookup_enum_offset(this._handle, value_name);
    }

    as_enumeration_type(): enumeration_type {
        const result = native.enumeration_type_as_enumeration_type(this._handle);
        return result === null ? null as unknown as enumeration_type : new enumeration_type(result);
    }

}

export class attribute {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    static with_name_type_of_attribute_optional(name: string, type_of_attribute: parameter_type, optional: boolean): attribute {
        return new attribute(native.attribute_new_with_name_type_of_attribute_optional(name, type_of_attribute, optional));
    }

    name(): string {
        return native.attribute_name(this._handle);
    }

    type_of_attribute(): parameter_type {
        const result = native.attribute_type_of_attribute(this._handle);
        return result === null ? null as unknown as parameter_type : new parameter_type(result);
    }

    optional(): boolean {
        return native.attribute_optional(this._handle);
    }

}

export class inverse_attribute {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    name(): string {
        return native.inverse_attribute_name(this._handle);
    }

    bound1(): number {
        return native.inverse_attribute_bound1(this._handle);
    }

    bound2(): number {
        return native.inverse_attribute_bound2(this._handle);
    }

    attribute_reference(): attribute {
        const result = native.inverse_attribute_attribute_reference(this._handle);
        return result === null ? null as unknown as attribute : new attribute(result);
    }

}

export class entity {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    is_abstract(): boolean {
        return native.entity_is_abstract(this._handle);
    }

    attributes(): attribute[] {
        const result = native.entity_attributes(this._handle) as unknown[];
        return result.map((item) => new attribute(item));
    }

    inverse_attributes(): inverse_attribute[] {
        const result = native.entity_inverse_attributes(this._handle) as unknown[];
        return result.map((item) => new inverse_attribute(item));
    }

    all_attributes(): attribute[] {
        const result = native.entity_all_attributes(this._handle) as unknown[];
        return result.map((item) => new attribute(item));
    }

    all_inverse_attributes(): inverse_attribute[] {
        const result = native.entity_all_inverse_attributes(this._handle) as unknown[];
        return result.map((item) => new inverse_attribute(item));
    }

    attribute_by_index(index: number): attribute {
        const result = native.entity_attribute_by_index(this._handle, index);
        return result === null ? null as unknown as attribute : new attribute(result);
    }

    attribute_count(): number {
        return native.entity_attribute_count(this._handle);
    }

}

export class schema_definition {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    declaration_by_name_with_name(name: string): declaration {
        const result = native.schema_definition_declaration_by_name_with_name(this._handle, name);
        return result === null ? null as unknown as declaration : new declaration(result);
    }

    declaration_by_name_with_declaration_index(declaration_index: number): declaration {
        const result = native.schema_definition_declaration_by_name_with_declaration_index(this._handle, declaration_index);
        return result === null ? null as unknown as declaration : new declaration(result);
    }

    declarations(): declaration[] {
        const result = native.schema_definition_declarations(this._handle) as unknown[];
        return result.map((item) => new declaration(item));
    }

    type_declarations(): type_declaration[] {
        const result = native.schema_definition_type_declarations(this._handle) as unknown[];
        return result.map((item) => new type_declaration(item));
    }

    select_types(): select_type[] {
        const result = native.schema_definition_select_types(this._handle) as unknown[];
        return result.map((item) => new select_type(item));
    }

    enumeration_types(): enumeration_type[] {
        const result = native.schema_definition_enumeration_types(this._handle) as unknown[];
        return result.map((item) => new enumeration_type(item));
    }

    name(): string {
        return native.schema_definition_name(this._handle);
    }

}

export class schema_registry {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    bind(schema: schema_definition): void {
        native.schema_registry_bind(this._handle, schema);
    }

    get(schema_name: string): schema_definition {
        const result = native.schema_registry_get(this._handle, schema_name);
        return result === null ? null as unknown as schema_definition : new schema_definition(result);
    }

    clear(): void {
        native.schema_registry_clear(this._handle);
    }

}

export class entity_instance {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    static create(): entity_instance {
        return new entity_instance(native.base_new());
    }

    declaration(): declaration {
        const result = native.base_declaration(this._handle);
        return result === null ? null as unknown as declaration : new declaration(result);
    }

    set_attribute_value_with_attribute_index_value(attribute_index: number, value: entity_instance): void {
        native.base_set_attribute_value_with_attribute_index_value(this._handle, attribute_index, value);
    }

    set_attribute_value_with_attribute_name_value(attribute_name: string, value: entity_instance): void {
        native.base_set_attribute_value_with_attribute_name_value(this._handle, attribute_name, value);
    }

    unset_attribute_value(attribute_index: number): void {
        native.base_unset_attribute_value(this._handle, attribute_index);
    }

    identity(): number {
        return native.base_identity(this._handle);
    }

    id(): number {
        return native.base_id(this._handle);
    }

    get_attribute_value(attribute_index: number): string | number | boolean | entity_instance | null {
        return native.base_get_attribute_value_variant(this._handle, attribute_index);
    }

    set_attribute_value(attribute_index: number, value: IfcopenshellAttributeValueVariantT): void {
        native.base_set_attribute_value_variant(this._handle, attribute_index, value);
    }

}

export class typed_entity_instance {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    get_inverse(attribute_name: string): typed_entity_instance[] {
        const result = native.entity_get_inverse(this._handle, attribute_name) as unknown[];
        return result.map((item) => new typed_entity_instance(item));
    }

}

export class select {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    static create(): select {
        return new select(native.select_new());
    }

    static with_value(value: entity_instance): select {
        return new select(native.select_new_with_value(value));
    }

    concrete(): entity_instance {
        const result = native.select_concrete(this._handle);
        return result === null ? null as unknown as entity_instance : new entity_instance(result);
    }

}

export class logger {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    set_product(product: entity_instance): void {
        native.logger_set_product(this._handle, product);
    }

    notice_with_message_instance(message: string, instance: entity_instance): void {
        native.logger_notice_with_message_instance_with_instance(this._handle, message, instance);
    }

    warning_with_message_instance(message: string, instance: entity_instance): void {
        native.logger_warning_with_message_instance_with_instance(this._handle, message, instance);
    }

    error_with_message_instance(message: string, instance: entity_instance): void {
        native.logger_error_with_message_instance_with_instance(this._handle, message, instance);
    }

    notice_with_exception_instance(exception: exception, instance: entity_instance): void {
        native.logger_notice_with_exception_instance_with_instance(this._handle, exception, instance);
    }

    warning_with_exception_instance(exception: exception, instance: entity_instance): void {
        native.logger_warning_with_exception_instance_with_instance(this._handle, exception, instance);
    }

    error_with_exception_instance(exception: exception, instance: entity_instance): void {
        native.logger_error_with_exception_instance_with_instance(this._handle, exception, instance);
    }

    status(message: string, new_line: boolean): void {
        native.logger_status_with_new_line(this._handle, message, new_line);
    }

    progress_bar(progress: number): void {
        native.logger_progress_bar(this._handle, progress);
    }

    get_log(): string {
        return native.logger_get_log(this._handle);
    }

    count(code: string): number {
        return native.logger_count(this._handle, code);
    }

    clear(): void {
        native.logger_clear(this._handle);
    }

    append(other: logger): void {
        native.logger_append(this._handle, other);
    }

    print_performance_stats(): void {
        native.logger_print_performance_stats(this._handle);
    }

    print_performance_stats_on_element_with_enabled(enabled: boolean): void {
        native.logger_print_performance_stats_on_element_with_enabled(this._handle, enabled);
    }

    print_performance_stats_on_element_overload_2(): boolean {
        return native.logger_print_performance_stats_on_element_overload_2(this._handle);
    }

}

export class full_buffer_impl {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    static create(): full_buffer_impl {
        return new full_buffer_impl(native.full_buffer_impl_new());
    }

    static with_path(path: string): full_buffer_impl {
        return new full_buffer_impl(native.full_buffer_impl_new_with_path(path));
    }

    size(): number {
        return native.full_buffer_impl_size(this._handle);
    }

    get_u32(position: number): number {
        return native.full_buffer_impl_get_u32(this._handle, position);
    }

    push_next_page(page_data: string): void {
        native.full_buffer_impl_push_next_page(this._handle, page_data);
    }

    drop_pages(up_to_position: number): void {
        native.full_buffer_impl_drop_pages(this._handle, up_to_position);
    }

}

export class paged_file_impl {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    static with_path_page_size_page_capacity(path: string, page_size: number, page_capacity: number): paged_file_impl {
        return new paged_file_impl(native.paged_file_impl_new_with_path_page_size_page_capacity(path, page_size, page_capacity));
    }

    size(): number {
        return native.paged_file_impl_size(this._handle);
    }

    get_u32(position: number): number {
        return native.paged_file_impl_get_u32(this._handle, position);
    }

    push_next_page(page_data: string): void {
        native.paged_file_impl_push_next_page(this._handle, page_data);
    }

    drop_pages(up_to_position: number): void {
        native.paged_file_impl_drop_pages(this._handle, up_to_position);
    }

}

export class pushed_sequential_impl {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    size(): number {
        return native.pushed_sequential_impl_size(this._handle);
    }

    get_u32(position: number): number {
        return native.pushed_sequential_impl_get_u32(this._handle, position);
    }

    push_next_page(page_data: string): void {
        native.pushed_sequential_impl_push_next_page(this._handle, page_data);
    }

    drop_pages(up_to_position: number): void {
        native.pushed_sequential_impl_drop_pages(this._handle, up_to_position);
    }

}

export class character_encoder {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    static with_input(input: string): character_encoder {
        return new character_encoder(native.character_encoder_new_with_input(input));
    }

}

export class file_open_status {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

}

export class token {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    static create(): token {
        return new token(native.token_new());
    }

    is_string(): boolean {
        return native.token_is_string(this._handle);
    }

    is_identifier(): boolean {
        return native.token_is_identifier(this._handle);
    }

    is_operator(): boolean {
        return native.token_is_operator(this._handle);
    }

    is_enumeration(): boolean {
        return native.token_is_enumeration(this._handle);
    }

    is_keyword(): boolean {
        return native.token_is_keyword(this._handle);
    }

    is_int(): boolean {
        return native.token_is_int(this._handle);
    }

    is_bool(): boolean {
        return native.token_is_bool(this._handle);
    }

    is_logical(): boolean {
        return native.token_is_logical(this._handle);
    }

    is_float(): boolean {
        return native.token_is_float(this._handle);
    }

    is_binary(): boolean {
        return native.token_is_binary(this._handle);
    }

    as_identifier(): number {
        return native.token_as_identifier(this._handle);
    }

    as_bool(): boolean {
        return native.token_as_bool(this._handle);
    }

    as_string(): string {
        return native.token_as_string(this._handle);
    }

    to_string(): string {
        return native.token_to_string(this._handle);
    }

}

export class enumeration_reference {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    static create(enumeration: enumeration_type, index: number): enumeration_reference {
        return new enumeration_reference(native.enumeration_reference_new_with_enumeration_index(enumeration, index));
    }

    index(): number {
        return native.enumeration_reference_index(this._handle);
    }

    enumeration(): enumeration_type {
        const result = native.enumeration_reference_enumeration(this._handle);
        return result === null ? null as unknown as enumeration_type : new enumeration_type(result);
    }

}

export class attribute_value {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    static create(): attribute_value {
        return new attribute_value(native.attribute_value_new());
    }

    is_null(): boolean {
        return native.attribute_value_is_null(this._handle);
    }

    size(): number {
        return native.attribute_value_size(this._handle);
    }

    type(): number {
        return native.attribute_value_type(this._handle);
    }

}

export class spf_header {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    static create(file: file, logger: logger): spf_header {
        return new spf_header(native.spf_header_new_with_file_logger(file, logger));
    }

    owner_file(file: file): void {
        native.spf_header_owner_file(this._handle, file);
    }

    assign(other: spf_header): void {
        native.spf_header_assign(this._handle, other);
    }

}

export class file {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    static with_path(path: string, filetype: number, readonly: boolean, logger: logger): file {
        return new file(native.file_new_with_path_with_filetype_readonly_logger(path, filetype, readonly, logger));
    }

    static with_data_data_size(data: Buffer, data_size: number, logger: logger): file {
        return new file(native.file_new_with_data_data_size_with_logger(data, data_size, logger));
    }

    static create_schema_filetype_path_logger(schema: schema_definition, filetype: number, path: string, logger: logger): file {
        return new file(native.file_new_with_schema_filetype_path_logger(schema, filetype, path, logger));
    }

    initialize(path: string, filetype: number, readonly: boolean): boolean {
        return native.file_initialize_with_filetype_readonly(this._handle, path, filetype, readonly);
    }

    bypass_type(type_name: string): void {
        native.file_bypass_type(this._handle, type_name);
    }

    good(): file_open_status {
        const result = native.file_good(this._handle);
        return result === null ? null as unknown as file_open_status : new file_open_status(result);
    }

    instances_by_type_with_declaration(declaration: declaration): entity_instance[] {
        const result = native.file_instances_by_type_with_declaration(this._handle, declaration) as unknown[];
        return result.map((item) => new entity_instance(item));
    }

    instances_by_type_excl_subtypes_with_declaration(declaration: declaration): entity_instance[] {
        const result = native.file_instances_by_type_excl_subtypes_with_declaration(this._handle, declaration) as unknown[];
        return result.map((item) => new entity_instance(item));
    }

    instances_by_type_with_type_name(type_name: string): entity_instance[] {
        const result = native.file_instances_by_type_with_type_name(this._handle, type_name) as unknown[];
        return result.map((item) => new entity_instance(item));
    }

    instances_by_type_excl_subtypes_with_type_name(type_name: string): entity_instance[] {
        const result = native.file_instances_by_type_excl_subtypes_with_type_name(this._handle, type_name) as unknown[];
        return result.map((item) => new entity_instance(item));
    }

    instances_by_reference(reference_id: number): entity_instance[] {
        const result = native.file_instances_by_reference(this._handle, reference_id) as unknown[];
        return result.map((item) => new entity_instance(item));
    }

    instance_by_id(instance_id: number): entity_instance {
        const result = native.file_instance_by_id(this._handle, instance_id);
        return result === null ? null as unknown as entity_instance : new entity_instance(result);
    }

    instance_by_guid(global_id: string): entity_instance {
        const result = native.file_instance_by_guid(this._handle, global_id);
        return result === null ? null as unknown as entity_instance : new entity_instance(result);
    }

    get_inverse(instance_id: number, declaration: declaration, attribute_index: number): typed_entity_instance[] {
        const result = native.file_get_inverse(this._handle, instance_id, declaration, attribute_index) as unknown[];
        return result.map((item) => new typed_entity_instance(item));
    }

    get_total_inverses(instance_id: number): number {
        return native.file_get_total_inverses(this._handle, instance_id);
    }

    fresh_id(): number {
        return native.file_fresh_id(this._handle);
    }

    get_max_id(): number {
        return native.file_get_max_id(this._handle);
    }

    ifcroot_type(): declaration {
        const result = native.file_ifcroot_type(this._handle);
        return result === null ? null as unknown as declaration : new declaration(result);
    }

    recalculate_id_counter(): void {
        native.file_recalculate_id_counter(this._handle);
    }

    add_entity(entity: entity_instance, instance_id: number): entity_instance {
        const result = native.file_add_entity_with_instance_id(this._handle, entity, instance_id);
        return result === null ? null as unknown as entity_instance : new entity_instance(result);
    }

    remove_entity(entity: entity_instance): void {
        native.file_remove_entity(this._handle, entity);
    }

    header(): spf_header {
        const result = native.file_header(this._handle);
        return result === null ? null as unknown as spf_header : new spf_header(result);
    }

    schema(): schema_definition {
        const result = native.file_schema(this._handle);
        return result === null ? null as unknown as schema_definition : new schema_definition(result);
    }

    build_inverses_overload_1(): void {
        native.file_build_inverses_overload_1(this._handle);
    }

    register_inverse(referenced_id: number, from_entity: entity, instance_id: number, attribute_index: number): void {
        native.file_register_inverse(this._handle, referenced_id, from_entity, instance_id, attribute_index);
    }

    unregister_inverse(referenced_id: number, from_entity: entity, entity: entity_instance, attribute_index: number): void {
        native.file_unregister_inverse(this._handle, referenced_id, from_entity, entity, attribute_index);
    }

    add_type_ref(new_entity: entity_instance): void {
        native.file_add_type_ref(this._handle, new_entity);
    }

    remove_type_ref(new_entity: entity_instance): void {
        native.file_remove_type_ref(this._handle, new_entity);
    }

    process_deletion_inverse(entity: entity_instance): void {
        native.file_process_deletion_inverse(this._handle, entity);
    }

    build_inverses_with_entity(entity: entity_instance): void {
        native.file_build_inverses_with_entity(this._handle, entity);
    }

    create_with_declaration_instance_id(declaration: declaration, instance_id: number): entity_instance {
        const result = native.file_create_with_declaration_instance_id_with_instance_id(this._handle, declaration, instance_id);
        return result === null ? null as unknown as entity_instance : new entity_instance(result);
    }

    batch(): void {
        native.file_batch(this._handle);
    }

    unbatch(): void {
        native.file_unbatch(this._handle);
    }

    reset_identity_cache(): void {
        native.file_reset_identity_cache(this._handle);
    }

}

export class global_id {
    /** @internal */ readonly _handle: unknown;
    /** @internal */ constructor(handle: unknown) {
        this._handle = handle;
    }

    static create(logger: logger): global_id {
        return new global_id(native.global_id_new_with_logger(logger));
    }

    static with_value(value: string, logger: logger): global_id {
        return new global_id(native.global_id_new_with_value_with_logger(value, logger));
    }

    formatted(): string {
        return native.global_id_formatted(this._handle);
    }

}
