// This file was generated with the assistance of an AI coding tool.
//
// The Phase 1 primitive layer -- every `file`/`entity_instance` primitive and the
// full schema-introspection class set (`declaration`, `entity`, `attribute`,
// `schema_definition`, ...), generated by wrappergen from the real C++ core -- see
// planning/ifcopenshell-ts/20-roadmap.md's Phase 1 and 10-architecture.md SS2. These
// are deliberately the *raw* primitives, named and shaped mechanically after their
// C++/Python counterparts (`file.instance_by_id(...)`, not a friendly
// `file.byId(...)`), still re-exported here as the documented escape hatch (matching
// Python's own `ifcopenshell_wrapper` submodule staying reachable alongside the
// friendly `ifcopenshell.file`/`ifcopenshell.entity_instance` API).
export * from "./native/ifcopenshell_native";

// Phase 2: `IfcFile`/`EntityInstance`, near-verbatim ports of `file_mixin`/
// `entity_instance_mixin` (see file.ts/entityInstance.ts's own doc comments for the
// exact scope and disclosed deviations), plus the small standalone modules ported
// alongside them (planning/ifcopenshell-ts/20-roadmap.md's Phase 2 task list).
export { IfcFile, Transaction, UndoSystemError } from "./file";
export type { TransactionOperation, ElementInverses, InverseReference } from "./file";
export { EntityInstance, AttributeCategory } from "./entityInstance";
export { settings } from "./settings";
export * as guid from "./guid";
export * as template from "./template";

// This chunk (planning/ifcopenshell-ts/10-architecture.md SS6): the attribute-metadata
// cache backing `EntityInstance`'s `Proxy` (re-exported mainly for the differential
// cache-correctness test, `test/attributeCache.test.ts`, and for anyone wanting the raw
// `AttributeMeta` shape directly) and the schema-driven `.d.ts` generator's typed
// output namespaces (`tools/generate-dts.ts` -> `src/generated/*.d.ts`).
export type { AttributeMeta, ClassAttributeCache } from "./attributeCache";
export { getClassAttributeMeta } from "./attributeCache";

// Phase 3, chunk 1: `ifcopenshell.util.element`'s pset/qto and type/material/style
// query functions (planning/ifcopenshell-ts/20-roadmap.md Phase 3) -- see
// `util/element.ts`'s own header comment for this chunk's exact scope and disclosed
// findings. Namespaced as `util.element.getPset(...)`, mirroring Python's
// `ifcopenshell.util.element.get_pset(...)` (see `util/index.ts`).
export * as util from "./util";
