// This file was generated with the assistance of an AI coding tool.
//
// Phase 1 primitive layer: every `file`/`entity_instance` primitive and the full
// schema-introspection class set (`declaration`, `entity`, `attribute`,
// `schema_definition`, ...), generated by wrappergen from the real C++ core -- see
// planning/ifcopenshell-ts/20-roadmap.md's Phase 1 and 10-architecture.md SS2.
//
// These are deliberately the *raw* primitives, named and shaped mechanically after
// their C++/Python counterparts (`file.instance_by_id(...)`, not a friendly
// `file.byId(...)`) -- Phase 2 (not yet built) ports `file_mixin`/`entity_instance_mixin`
// on top of this surface, exactly like SWIG's Python binding layers a hand-written
// mixin over its own generated primitives (research/01-python-core-and-lowlevel.md SS1).
// This package has no friendly `IfcFile`/`EntityInstance` API yet -- that is Phase 2's
// deliverable, not this one's.
export * from "./native/ifcopenshell_native";
